### ISSUE TITLE
Verification Email sent multiple times

### ISSUE THREAD

**Issue by Shanakor** [Shanakor/ForEvernote_Android#1]
Occurs only sporadically.

**Comment by meik99** [comment]
Switched call of addAuthChangeListener. Time will tell if this helps

**Comment by meik99** [comment]
addAuthChangeListener will only be called when clicking login or register and not on startup. Pretty sure this fixed it

**Comment by Shanakor** [comment]
Actually this is genius xD awesome

**Comment by Shanakor** [comment]
Has not occured anymore 

(I somehow want to mark that we have to be careful when fixing issue #2, do you know how?
