### ISSUE TITLE
When pressing back in MainActivity VerificationActivity pops up

### ISSUE THREAD

**Issue by meik99** [Shanakor/ForEvernote_Android#5]
Should instead go to login screen

**Comment by meik99** [comment]
Fixed. Entry in manifest must have android:noHistory set to true

**Comment by Shanakor** [comment]
Ow gawd this is so awesome xDD awesome solution. Did you know that you can
just fucking reply to the notification emails? O.o

Am 02.02.2017 5:45 nachm. schrieb "Michael" <notifications@github.com>:
